import { InsertSneaker } from "@/lib/db/schema";

export const sneakersData: Array<InsertSneaker> = [
	{
		brandId: 1,
		name: "Air Jordan 1",
		slug: "air-jordan-1",
		color: "White",
		price: 100,
		image:
			"https://image.goat.com/375/attachments/product_template_pictures/images/010/223/048/original/13607_00.png.png",
		shortDescription: "The Air Jordan 1 is a classic sneaker that was first released in 1985.",
	},
	{
		brandId: 1,
		name: "Air Jordan 1 Retro High OG Shadow",
		slug: "air-jordan-1-retro-high-og-shadow-2018-555088-013",
		color: "Black",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/011/119/994/original/218099_00.png.png",
		shortDescription:
			"\"This Nike Air Jordan 1 Retro High OG 'Shadow' 2018 is a retro re-release of an original 1985 colorway. The shoe features a black and medium grey leather upper with a white midsole and black outsole. ...",
		longDescription:
			"\"This Nike Air Jordan 1 Retro High OG 'Shadow' 2018 is a retro re-release of an original 1985 colorway. The shoe features a black and medium grey leather upper with a white midsole and black outsole. It also features OG Nike Air branding on the tongue and the Wings logo on the ankle collar. It was last retroed in 2013",
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 4 Retro OG Bred",
		slug: "air-jordan-4-retro-og-gs-bred-408452-060",
		color: "Black",
		price: 140,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/806/444/original/507844_00.png.png",
		shortDescription: "The Air Jordan is a Black sneaker from Air Jordan.",
		longDescription: null,
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 11 Retro Space Jam",
		slug: "air-jordan-11-retro-space-jam-378037-003",
		color: "Black",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/008/654/900/original/52015_00.png.png",
		shortDescription:
			'"The Air Jordan 11 Retro ‘Space Jam’ 2016 commemorates the 20th anniversary of the movie ‘Space Jam.’ Worn by Michael Jordan as a Player Exclusive (PE) in both the movie and the 1995 NBA Playoffs',
		longDescription:
			'"The Air Jordan 11 Retro ‘Space Jam’ 2016 commemorates the 20th anniversary of the movie ‘Space Jam.’ Worn by Michael Jordan as a Player Exclusive (PE) in both the movie and the 1995 NBA Playoffs',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 11 Retro Gym Red",
		slug: "air-jordan-11-retro-gym-red-378037-623-abb4fed8-42d8-4998-9858-47500cc06cc7",
		color: "Red",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/008/870/353/original/235806_00.png.png",
		shortDescription: '"For Chicago Bulls Fans',
		longDescription: '"For Chicago Bulls Fans',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 11 Retro Legend Blue",
		slug: "air-jordan-11-retro-legend-blue-378037-117",
		color: "White",
		price: 200,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/010/223/048/original/13607_00.png.png",
		shortDescription:
			'"The Air Jordan 11 Retro ‘Legend Blue’ 2014 was based on the 1996 Jordan 11 ‘Columbia’ first worn by Jordan during the 1996 NBA All-Star Game. Inspired by the classic colorway Jordan wore as a Tarheel',
		longDescription:
			'"The Air Jordan 11 Retro ‘Legend Blue’ 2014 was based on the 1996 Jordan 11 ‘Columbia’ first worn by Jordan during the 1996 NBA All-Star Game. Inspired by the classic colorway Jordan wore as a Tarheel',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 1 Retro High OG Panda",
		slug: "wmns-air-jordan-1-retro-high-og-panda-cd0461-007",
		color: "Black",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/545/481/original/509480_00.png.png",
		shortDescription: "The Air Jordan is a Black sneaker from Air Jordan.",
		longDescription: null,
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 1 Mid",
		slug: "air-jordan-1-mid-554724-065",
		color: "Black",
		price: 110,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/012/910/690/original/554724_065.png.png",
		shortDescription: "The Air Jordan is a Black sneaker from Air Jordan.",
		longDescription: null,
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 4 Retro Bred",
		slug: "air-jordan-4-retro-bred-2019-308497-060",
		color: "Black",
		price: 200,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/806/485/original/461782_00.png.png",
		shortDescription:
			'"The 2019 edition of the Air Jordan 4 ‘Bred’ celebrates the 30th anniversary of the classic silhouette',
		longDescription:
			'"The 2019 edition of the Air Jordan 4 ‘Bred’ celebrates the 30th anniversary of the classic silhouette',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 6 Retro Black Infrared",
		slug: "air-jordan-6-retro-black-infrared-384664-060",
		color: "Black",
		price: 200,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/018/675/311/original/464372_00.png.png",
		shortDescription: '"The 2019 edition of the Air Jordan 6 Retro ‘Infrared’ is true to the original colorway',
		longDescription: '"The 2019 edition of the Air Jordan 6 Retro ‘Infrared’ is true to the original colorway',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 12 Retro Reptile",
		slug: "wmns-air-jordan-12-retro-reptile-ao6068-007",
		color: "Black",
		price: 190,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/042/384/original/500924_00.png.png",
		shortDescription:
			"\"The Wmns Air Jordan 12 Retro 'Reptile' sneaker draws details from the 1996 classic and elevates them with luxe style additions. This April 2019-released",
		longDescription:
			"\"The Wmns Air Jordan 12 Retro 'Reptile' sneaker draws details from the 1996 classic and elevates them with luxe style additions. This April 2019-released",
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 4 Retro Laser",
		slug: "air-jordan-4-retro-laser-aj4-laser",
		color: "Black",
		price: 200,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/018/071/547/original/479524_00.png.png",
		shortDescription: '"Releasing in January 2019',
		longDescription: '"Releasing in January 2019',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Off-White x Air Jordan 1 Retro High OG Powder Blue",
		slug: "off-white-x-air-jordan-1-retro-high-og-powder-blue-aq0818-148",
		color: "Blue",
		price: 190,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/012/219/518/original/335047_00.png.png",
		shortDescription: '"Inspired by Michael Jordan’s alma mater',
		longDescription: '"Inspired by Michael Jordan’s alma mater',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Trophy Room x Air Jordan 5 Retro Ice Blue",
		slug: "trophy-room-x-air-jordan-5-retro-ice-blue-tr-jsp-5-ice",
		color: "Blue",
		price: 200,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/474/777/original/TR_JSP_5_ICE.png.png",
		shortDescription: "The Air Jordan is a Blue sneaker from Air Jordan.",
		longDescription: null,
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Travis Scott x Air Jordan 4 Retro Cactus Jack",
		slug: "travis-scott-x-air-jordan-4-retro-cactus-jack-308497-406",
		color: "Blue",
		price: 225,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/012/478/518/original/365514_00.png.png",
		shortDescription: '"Music artist Travis Scott hails from Houston',
		longDescription: '"Music artist Travis Scott hails from Houston',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 1 Retro High OG Rookie of the Year",
		slug: "air-jordan-1-retro-high-og-rookie-of-the-year-555088-700",
		color: "Brown",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/016/152/710/original/402491_00.png.png",
		shortDescription: '"In 1985',
		longDescription: '"In 1985',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Travis Scott x Air Jordan 1 Retro High OG",
		slug: "travis-scott-x-air-jordan-1-retro-high-og-cd4487-100",
		color: "Brown",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/018/783/111/original/488879_00.png.png",
		shortDescription: '"The Travis Scott x Air Jordan 1 Retro High features a new look on the iconic silhouette',
		longDescription: '"The Travis Scott x Air Jordan 1 Retro High features a new look on the iconic silhouette',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Patta x Air Jordan 7 Retro OG Shimmer",
		slug: "patta-x-air-jordan-7-retro-og-sp-shimmer-patta-aj7-shm",
		color: "Brown",
		price: 200,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/321/847/original/473391_00.png.png",
		shortDescription: '"Amsterdam-based boutique and streetwear brand',
		longDescription: '"Amsterdam-based boutique and streetwear brand',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 1 Retro High OG Turbo Green",
		slug: "air-jordan-1-retro-high-og-turbo-green-555088-311",
		color: "Green",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/018/552/901/original/404758_00.png.png",
		shortDescription:
			'"The Air Jordan 1 Retro High OG ‘Turbo Green’ complements the silhouette’s clean lines with a classic two-tone design. A textured white leather base is contrasted by soft suede overlays in Turbo Green...',
		longDescription:
			'"The Air Jordan 1 Retro High OG ‘Turbo Green’ complements the silhouette’s clean lines with a classic two-tone design. A textured white leather base is contrasted by soft suede overlays in Turbo Green. The latter design element is burnished to give off a vintage aesthetic',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 1 Retro High OG Crimson Tint",
		slug: "air-jordan-1-retro-high-og-crimson-tint-555088-081",
		color: "Pink",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/249/059/original/485842_00.png.png",
		shortDescription: '"The Air Jordan 1 Retro High OG ‘Crimson Tint’ showcases a simple two-tone design',
		longDescription: '"The Air Jordan 1 Retro High OG ‘Crimson Tint’ showcases a simple two-tone design',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 11 Retro Low Orange Trance",
		slug: "wmns-air-jordan-11-retro-low-orange-trance-ah7860-106",
		color: "Pink",
		price: 185,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/357/907/original/478963_00.png.png",
		shortDescription: '"An original colorway of the Air Jordan 11 Low back in 2001',
		longDescription: '"An original colorway of the Air Jordan 11 Low back in 2001',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 1 High OG Defiant",
		slug: "air-jordan-1-high-og-defiant-cd6578-507",
		color: "Purple",
		price: 175,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/270/533/original/CD6578_507.png.png",
		shortDescription: "The Air Jordan is a Purple sneaker from Air Jordan.",
		longDescription: null,
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 1 Retro High OG",
		slug: "air-jordan-1-retro-high-og-555088-610",
		color: "Red",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/009/559/594/original/144690_00.png.png",
		shortDescription: '"Arriving in stores in February 2018',
		longDescription: '"Arriving in stores in February 2018',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Spider-Verse x Air Jordan 1 Retro High OG Origin Story",
		slug: "spider-verse-x-air-jordan-1-retro-high-og-origin-story",
		color: "Red",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/016/867/969/original/478648_00.png.png",
		shortDescription:
			'"Air Jordan 1 Retro High OG ‘Origin Story’ was made to celebrate the animated film Spider-Man: Into the Spider-Verse. The high-top features a design that mirrors the pair worn by character Miles Moral...',
		longDescription:
			'"Air Jordan 1 Retro High OG ‘Origin Story’ was made to celebrate the animated film Spider-Man: Into the Spider-Verse. The high-top features a design that mirrors the pair worn by character Miles Morales',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 12 Retro Bulls",
		slug: "air-jordan-12-retro-bulls-130690-601",
		color: "Red",
		price: 190,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/016/596/414/original/376931_00.png.png",
		shortDescription:
			'"The Air Jordan 12 Retro ‘Gym Red’ presents a monochromatic take on Tinker Hatfield’s 1996 design. The entirety of the mid-top silhouette is dipped in red',
		longDescription:
			'"The Air Jordan 12 Retro ‘Gym Red’ presents a monochromatic take on Tinker Hatfield’s 1996 design. The entirety of the mid-top silhouette is dipped in red',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 11 Retro Low Snakeskin",
		slug: "air-jordan-11-retro-low-snakeskin-2019-cd6846-002",
		color: "Red",
		price: 185,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/219/116/original/CD6846_002.png.png",
		shortDescription:
			"\"The Air Jordan 11 Retro Low's iconic identity was founded when Michael Jordan returned to the game in 1995. Surfacing in June 2019",
		longDescription:
			"\"The Air Jordan 11 Retro Low's iconic identity was founded when Michael Jordan returned to the game in 1995. Surfacing in June 2019",
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 1 Retro High SB Light Bone",
		slug: "air-jordan-1-retro-high-sb-light-bone-cd6578-006",
		color: "White",
		price: 0,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/147/976/original/497870_00.png.png",
		shortDescription:
			'"The Air Jordan SB 1 Retro High is representative of the decades-old influence that the iconic shoe has had on skate culture. Revealed in May 2019',
		longDescription:
			'"The Air Jordan SB 1 Retro High is representative of the decades-old influence that the iconic shoe has had on skate culture. Revealed in May 2019',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 1 Retro High OG Black Phantom",
		slug: "air-jordan-1-retro-high-og-black-phantom-555088-160",
		color: "White",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/095/762/original/411931_00.png.png",
		shortDescription: '"Instead of the usual two-tone color blocking',
		longDescription: '"Instead of the usual two-tone color blocking',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Sneaker Politics x Air Jordan 1 Low Block Party",
		slug: "sneaker-politics-x-air-jordan-1-low-block-party-sp-aj1-low-bp",
		color: "White",
		price: 100,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/317/617/original/SP_AJ1_LOW_BP.png.png",
		shortDescription: "The Air Jordan is a White sneaker from Air Jordan.",
		longDescription: null,
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 11 Retro Platinum Tint",
		slug: "air-jordan-11-retro-platinum-tint-378037-016",
		color: "White",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/015/392/851/original/429772_00.png.png",
		shortDescription:
			'"The Air Jordan 11 Retro ‘Platinum Tint’ does away with the one detail most commonly associated with the classic silhouette—its shiny patent leather overlay. Instead',
		longDescription:
			'"The Air Jordan 11 Retro ‘Platinum Tint’ does away with the one detail most commonly associated with the classic silhouette—its shiny patent leather overlay. Instead',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 11 Retro Concord",
		slug: "air-jordan-11-retro-concord-2018-378037-100",
		color: "White",
		price: 220,
		image: "https://image.goat.com/750/attachments/product_template_pictures/images/016/934/177/original/351614_00.png",
		shortDescription:
			'"The 2018 edition of the Air Jordan 11 Retro ‘Concord’ features ‘45’ stamped on the black heel tab—a nod to the jersey number that Michael Jordan wore upon his return to basketball following his first...',
		longDescription:
			'"The 2018 edition of the Air Jordan 11 Retro ‘Concord’ features ‘45’ stamped on the black heel tab—a nod to the jersey number that Michael Jordan wore upon his return to basketball following his first retirement. The rest of the build keeps the shoe’s signature details intact',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 11 Retro Low Navy Snakeskin",
		slug: "air-jordan-11-retro-low-snakeskin-2019-cd6846-102",
		color: "White",
		price: 185,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/310/667/original/459705_00.png.png",
		shortDescription:
			'"The Air Jordan 11 Retro Low ‘Navy Snakeskin’ returns for the first time since 2000. A true retro to the original',
		longDescription:
			'"The Air Jordan 11 Retro Low ‘Navy Snakeskin’ returns for the first time since 2000. A true retro to the original',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Jordan 4 Retro OG Cement",
		slug: "air-jordan-retro-4-og-cement-2016-836015-192",
		color: "White",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/008/654/831/original/31342_00.png.png",
		shortDescription:
			"\"The Air Jordan 4 Retro OG 'Cement’ 2016 was one of the original four colorways released in 1989. The sneaker features the original White",
		longDescription:
			"\"The Air Jordan 4 Retro OG 'Cement’ 2016 was one of the original four colorways released in 1989. The sneaker features the original White",
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 8,
		name: "Champion Rally Pro Black",
		slug: "rally-pro-black-cm100018m",
		color: "Black",
		price: 100,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/015/567/335/original/CM100018M.png.png",
		shortDescription: '"The Champion Rally Pro sneaker packages street style in a sleek',
		longDescription: '"The Champion Rally Pro sneaker packages street style in a sleek',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 3,
		name: "Tyler the Creator x Foot Locker x Chuck 70 Artist Series",
		slug: "tyler-the-creator-x-foot-locker-x-chuck-70-artist-series-ttc-fl-c70-crm",
		color: "Cream",
		price: 100,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/018/552/840/original/476518_00.png.png",
		shortDescription: '"Tyler',
		longDescription: '"Tyler',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 3,
		name: "Chuck Taylor Hi x Comme des Garçons Play",
		slug: "ct-hi-x-comme-des-garcons-play-150205c",
		color: "White",
		price: 120,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/015/298/767/original/77243_00.png.png",
		shortDescription: '"This Comme des Garçons x Chuck Taylor All Star Hi features an off-white canvas upper',
		longDescription: '"This Comme des Garçons x Chuck Taylor All Star Hi features an off-white canvas upper',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 9,
		name: "Gucci Pursuit 72 Rubber Slides Black",
		slug: "gucci-pursuit-72-rubber-slides-black-308234-gib10-1098",
		color: "Black",
		price: 210,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/009/249/006/original/259509_00.png.png",
		shortDescription:
			"\"The Gucci Pursuit ‘72 Rubber Slide in ‘Black’ sneaker pays homage to the fashion house's roots with the iconic Web stripe—first developed by Gucci in the 1950s—taking the stage. The minimal",
		longDescription:
			"\"The Gucci Pursuit ‘72 Rubber Slide in ‘Black’ sneaker pays homage to the fashion house's roots with the iconic Web stripe—first developed by Gucci in the 1950s—taking the stage. The minimal",
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Friends x Kyrie 5",
		slug: "friends-x-kyrie-5-ao2918-006",
		color: "Black",
		price: 130,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/840/270/original/491192_00.png.png",
		shortDescription: "The Nike is a Black sneaker from Nike.",
		longDescription: null,
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Max 97 Neon Seoul",
		slug: "air-max-97-neon-seoul-am-97-seoul",
		color: "Black",
		price: 200,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/627/570/original/491891_00.png.png",
		shortDescription: '"In celebration of Air Max Day',
		longDescription: '"In celebration of Air Max Day',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Fear of God Strap Black",
		slug: "air-fear-of-god-strap-black-at8087-002",
		color: "Black",
		price: 190,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/545/549/original/489359_00.png.png",
		shortDescription: '"Nike and frequent collaborator Fear Of God designer',
		longDescription: '"Nike and frequent collaborator Fear Of God designer',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Off-White x Air Max 90 Black",
		slug: "off-white-x-air-max-90-black-aa7293-001",
		color: "Black",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/017/763/484/original/466439_00.png.png",
		shortDescription: '"The Off-White x Air Max 90 ‘Black’ offers a unique blend of materials on the upper',
		longDescription: '"The Off-White x Air Max 90 ‘Black’ offers a unique blend of materials on the upper',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Off-White x Air Presto",
		slug: "off-white-x-air-presto-aa3830-002",
		color: "Black",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/012/750/761/original/351623_00.png.png",
		shortDescription:
			'"This monochromatic take on the Air Presto is the second time Virgil Abloh and Nike collaborated on this iconic silhouette. The July 2018 iteration came a few mere months after it’s two-tone predecess...',
		longDescription:
			'"This monochromatic take on the Air Presto is the second time Virgil Abloh and Nike collaborated on this iconic silhouette. The July 2018 iteration came a few mere months after it’s two-tone predecessor made it’s debut as part of Abloh and Nike’s ‘The Ten’ Collection. This pair showcases an all-black finish',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Sacai x LDV Waffle Varsity Blue",
		slug: "sacai-x-ldv-waffle-varsity-blue-bv0073-400",
		color: "Blue",
		price: 180,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/019/246/220/original/491897_00.png.png",
		shortDescription: '"Sacai and Nike collaborate again',
		longDescription: '"Sacai and Nike collaborate again',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Blazer Mid 77 Vintage Cream Navy",
		slug: "blazer-mid-77-vintage-cream-navy-cd9318-100",
		color: "Cream",
		price: 110,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/545/501/original/507173_00.png.png",
		shortDescription: "The Nike is a Cream sneaker from Nike.",
		longDescription: null,
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Atmos x Air Max 2 Light Logos",
		slug: "atmos-x-air-max-2-light-logos-bv7406-001",
		color: "Multi-Color",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/249/043/original/494127_00.png.png",
		shortDescription: '"First spotted on the feet of atmos creative director Hirofumi Kojima during ComplexCon 2018',
		longDescription: '"First spotted on the feet of atmos creative director Hirofumi Kojima during ComplexCon 2018',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Force 1 07 LV8 Team Orange",
		slug: "air-force-1-07-lv8-team-orange-aj7747-800",
		color: "Orange",
		price: 100,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/019/994/877/original/AJ7747_800.png.png",
		shortDescription: "The Nike is a Orange sneaker from Nike.",
		longDescription: null,
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Max 90 QS Mars Landing",
		slug: "air-max-90-qs-mars-landing-cd0920-600",
		color: "Red",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/019/804/999/original/488028_00.png.png",
		shortDescription:
			"\"The Nike Air Max 90 QS 'Mars Landing' sneaker was released in March 2019 as an homage to the rover landing expedition on Mars. Fusing elements of the 1990 classic with official imagery of the Red Pla...",
		longDescription:
			"\"The Nike Air Max 90 QS 'Mars Landing' sneaker was released in March 2019 as an homage to the rover landing expedition on Mars. Fusing elements of the 1990 classic with official imagery of the Red Planet",
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Off-White x Air Max 90 Desert Ore",
		slug: "off-white-x-air-max-90-desert-ore-aa7293-200",
		color: "Tan",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/017/794/455/original/394710_00.png.png",
		shortDescription:
			'"The Off-White x Air Max 90 ‘Desert Ore’ represents yet another of Virgil Abloh’s fanciful takes on the retro silhouette. Unlike its stark black and white counterparts',
		longDescription:
			'"The Off-White x Air Max 90 ‘Desert Ore’ represents yet another of Virgil Abloh’s fanciful takes on the retro silhouette. Unlike its stark black and white counterparts',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Off-White x Air VaporMax Part 2",
		slug: "off-white-x-air-vapormax-part-2-aa3831-100",
		color: "White",
		price: 250,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/010/564/058/original/303229_00.png.png",
		shortDescription:
			'"The April 2018 version of Virgil Abloh’s all-white Air VaporMax is mostly unchanged from the original pair from ‘The Ten.’ Stripped of color',
		longDescription:
			'"The April 2018 version of Virgil Abloh’s all-white Air VaporMax is mostly unchanged from the original pair from ‘The Ten.’ Stripped of color',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Travis Scott x Air Force 1 Sail",
		slug: "travis-scott-x-air-force-1-sail-aq4211-101",
		color: "White",
		price: 150,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/013/832/092/original/306892_00.png.png",
		shortDescription:
			'"The ‘Sail’ colorway of Travis Scott’s Air Force 1 represents the Houston rapper’s second collaboration with Nike on the classic silhouette. Aside from swapping out the all-white finish of its predece...',
		longDescription:
			'"The ‘Sail’ colorway of Travis Scott’s Air Force 1 represents the Houston rapper’s second collaboration with Nike on the classic silhouette. Aside from swapping out the all-white finish of its predecessor with slightly darker Sail',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Force 1 Low Earth Day",
		slug: "air-force-1-low-earth-day-ci5545-100",
		color: "White",
		price: 100,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/881/688/original/508101_00.png.png",
		shortDescription: "The Nike is a White sneaker from Nike.",
		longDescription: null,
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Force 1 Low GS Have a Nike Day",
		slug: "air-force-1-low-gs-have-a-nike-day-white-af1-gs-hand-wht",
		color: "White",
		price: 100,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/019/367/662/original/484799_00.png.png",
		shortDescription: "The Nike is a White sneaker from Nike.",
		longDescription: null,
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Force 1 07 Low University Blue",
		slug: "air-force-1-07-low-university-blue-ao2423-100",
		color: "White",
		price: 90,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/018/898/008/original/482531_00.png.png",
		shortDescription: "The Nike is a White sneaker from Nike.",
		longDescription: null,
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Nike Air Force 1 Low",
		slug: "nike-air-force-1-315122-111",
		color: "White",
		price: 90,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/010/222/352/original/240_00.png.png",
		shortDescription:
			"\"The Nike Air Force 1 Low is a modern take on the iconic white on white low top Air Force 1. Released in honor of the classic shoe's 25th anniversary in 2007",
		longDescription:
			"\"The Nike Air Force 1 Low is a modern take on the iconic white on white low top Air Force 1. Released in honor of the classic shoe's 25th anniversary in 2007",
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Max 97 Game Royal",
		slug: "air-max-97-game-royal-921826-404",
		color: "White",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/562/245/original/480142_00.png.png",
		shortDescription: "The Nike is a White sneaker from Nike.",
		longDescription: null,
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Fear of God Strap Light Bone",
		slug: "air-fear-of-god-strap-light-bone-at8087-001",
		color: "White",
		price: 190,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/627/586/original/487222_00.png.png",
		shortDescription: '"Created by acclaimed streetwear designer Jerry Lorenzo for release in April 2019',
		longDescription: '"Created by acclaimed streetwear designer Jerry Lorenzo for release in April 2019',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Fear of God Moccasin Pure Platinum",
		slug: "air-fear-of-god-moccasin-pure-platinum-afog-moc-plat",
		color: "White",
		price: 170,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/737/643/original/504006_00.png.png",
		shortDescription: "\"From streetwear fashion designer Jerry Lorenzo comes the Air Fear of God Moc 'Pure Platinum",
		longDescription: "\"From streetwear fashion designer Jerry Lorenzo comes the Air Fear of God Moc 'Pure Platinum",
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Cactus Plant Flea Market x Air VaporMax",
		slug: "cactus-plant-flea-market-x-air-vapormax-2019-cpfm-vapormax",
		color: "Grey",
		price: 250,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/321/832/original/503571_00.png.png",
		shortDescription: '"In honor of Air Max Day 2019',
		longDescription: '"In honor of Air Max Day 2019',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Max 97 Triple White",
		slug: "air-max-97-triple-white-921826-101",
		color: "White",
		price: 160,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/010/988/952/original/180155_00.png.png",
		shortDescription:
			"\"The Nike Air Max 97 'Triple White' features a white leather and mesh upper with Wolf Grey accents. Released in August of 2017",
		longDescription:
			"\"The Nike Air Max 97 'Triple White' features a white leather and mesh upper with Wolf Grey accents. Released in August of 2017",
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 1,
		name: "Air Max 270 White",
		slug: "air-max-270-white-ah8050-100",
		color: "White",
		price: 150,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/010/634/133/original/303217_00.png.png",
		shortDescription: '"Released in March 2018',
		longDescription: '"Released in March 2018',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 5,
		name: "Vans Old Skool Yacht Club",
		slug: "old-skool-yacht-club-vn0a38g1r1q",
		color: "Multi-Color",
		price: 60,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/011/051/956/original/335725_00.png.png",
		shortDescription:
			'"The Vans Old Skool ‘Yacht Club’ showcases bold color blocking inspired by traditional nautical flags. The shoe’s upper is executed with canvas quarter panels in kelly green',
		longDescription:
			'"The Vans Old Skool ‘Yacht Club’ showcases bold color blocking inspired by traditional nautical flags. The shoe’s upper is executed with canvas quarter panels in kelly green',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 350 V2 Black",
		slug: "yeezy-boost-350-v2-black-yzy-350-v2-blk",
		color: "Black",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/624/696/original/FU9013.png.png",
		shortDescription:
			'"The adidas Yeezy Boost 350 V2 lives up to its cult appeal through evolved design elements and advanced technology. Released June 2019',
		longDescription:
			'"The adidas Yeezy Boost 350 V2 lives up to its cult appeal through evolved design elements and advanced technology. Released June 2019',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 700 V2 Vanta",
		slug: "yeezy-boost-700-v2-vanta-yzy-700-v2-vanta",
		color: "Black",
		price: 300,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/147/972/original/504187_00.png.png",
		shortDescription: "The adidas is a Black sneaker from adidas.",
		longDescription: null,
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 350 V2",
		slug: "yeezy-boost-350-v2-b37571",
		color: "Blue",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/008/707/328/original/152603_00.png.png",
		shortDescription:
			"\"The 5th Yeezy to drop since November 2017 — Yeezy Boost 350 V2 'Semi Frozen Yellow' and ‘Beluga 2.0",
		longDescription:
			"\"The 5th Yeezy to drop since November 2017 — Yeezy Boost 350 V2 'Semi Frozen Yellow' and ‘Beluga 2.0",
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 2,
		name: "Pharrell x Billionaire Boys Club x NMD Human Race Trail Blue Plaid",
		slug: "pharrell-x-billionaire-boys-club-x-nmd-human-race-trail-blue-plaid-ef7387",
		color: "Blue",
		price: 250,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/545/467/original/512006_00.png.png",
		shortDescription: "The adidas is a Blue sneaker from adidas.",
		longDescription: null,
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 700 Analog",
		slug: "yeezy-boost-700-analog-yeezy-boost-700-analog",
		color: "Cream",
		price: 300,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/287/568/original/480136_00.png.png",
		shortDescription:
			"\"Music and fashion icon Kanye West debuted the Yeezy Boost 700 at his Yeezy Season 5 fashion show in February 2017. This 'Analog' colorway released April 2019",
		longDescription:
			"\"Music and fashion icon Kanye West debuted the Yeezy Boost 700 at his Yeezy Season 5 fashion show in February 2017. This 'Analog' colorway released April 2019",
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy 350 V2 Glow in the Dark",
		slug: "yeezy-350-v2-glow-in-the-dark-eh5360",
		color: "Green",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/021/357/863/original/508082_00.png.png",
		shortDescription: '"Regarded as a cultural phenomenon',
		longDescription: '"Regarded as a cultural phenomenon',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 350 V2 Beluga 2.0",
		slug: "yeezy-boost-350-v2-beluga-2-0-ah2203",
		color: "Grey",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/008/654/534/original/152982_00.png.png",
		shortDescription: '"With its name coming from the colorway similarities found on the first Yeezy Boost 350 V2',
		longDescription: '"With its name coming from the colorway similarities found on the first Yeezy Boost 350 V2',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 700 Inertia",
		slug: "yeezy-boost-700-inertia-yeezy-boost-700-inertia",
		color: "Grey",
		price: 300,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/019/367/689/original/479750_00.png.png",
		shortDescription:
			'"The adidas Yeezy Boost 700 ‘Inertia’ is part of the Yeezy Season 8 lineup that launched March 2019. The ‘Inertia’ colorway showcases the original 700 upper',
		longDescription:
			'"The adidas Yeezy Boost 700 ‘Inertia’ is part of the Yeezy Season 8 lineup that launched March 2019. The ‘Inertia’ colorway showcases the original 700 upper',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 350 V2 Sesame",
		slug: "yeezy-boost-350-v2-sesame-f99710",
		color: "Grey",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/014/037/000/original/357808_00.png.png",
		shortDescription:
			'"The Yeezy Boost 350 V2 ‘Sesame’ features a refined color palette that complements the shoe’s minimalist build. The breathable Primeknit upper keeps the heel tab and distinct center stitch detailing b...',
		longDescription:
			'"The Yeezy Boost 350 V2 ‘Sesame’ features a refined color palette that complements the shoe’s minimalist build. The breathable Primeknit upper keeps the heel tab and distinct center stitch detailing but loses the mirrored ‘SPLY-350’ branding. Underneath',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Wave Runner 700",
		slug: "yeezy-wave-runner-700-76fa2bf7-9596-46cb-9842-e024a94baa6c",
		color: "Grey",
		price: 300,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/014/507/851/original/195483_00.png.png",
		shortDescription: '"This inaugural colorway of Kanye West’s Yeezy Wave Runner 700 launched in November 2017',
		longDescription: '"This inaugural colorway of Kanye West’s Yeezy Wave Runner 700 launched in November 2017',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 350 V2 Static",
		slug: "yeezy-boost-350-v2-static-ef2905",
		color: "Grey",
		price: 220,
		image: "https://image.goat.com/750/attachments/product_template_pictures/images/017/488/396/original/424152_00.png",
		shortDescription: '"The Yeezy Boost 350 V2 ‘Static Non-Reflective’ is designed to stand out',
		longDescription: '"The Yeezy Boost 350 V2 ‘Static Non-Reflective’ is designed to stand out',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 2,
		name: "Pharrell x Solar Hu Glide ST Chinese New Year",
		slug: "pharrell-x-solar-hu-glide-st-chinese-new-year-ee8701",
		color: "Red",
		price: 150,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/018/666/882/original/486579_00.png.png",
		shortDescription: '"Alongside an accompanying Crazy BYW',
		longDescription: '"Alongside an accompanying Crazy BYW',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 350 V2 Clay",
		slug: "yeezy-boost-350-v2-clay-yzy-350-v2-clay",
		color: "Tan",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/019/471/948/original/487214_00.png.png",
		shortDescription:
			'"The adidas Yeezy Boost 350 V2 ‘Clay’ updates the silhouette with a warm palette and semi-translucent',
		longDescription:
			'"The adidas Yeezy Boost 350 V2 ‘Clay’ updates the silhouette with a warm palette and semi-translucent',
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 350 V2 Cream White",
		slug: "yeezy-boost-350-v2-cream-white-cp9366",
		color: "White",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/014/822/680/original/116662_00.png.png",
		shortDescription: '"First released on April 29',
		longDescription: '"First released on April 29',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 700 Salt",
		slug: "yeezy-boost-700-salt-yzy-700-salt",
		color: "White",
		price: 300,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/018/951/283/original/492186_00.png.png",
		shortDescription:
			'"The Yeezy Boost 700 ‘Salt’ follows a design trail originally blazed by the Yeezy 500 in November 2018. Like its predecessor',
		longDescription:
			'"The Yeezy Boost 700 ‘Salt’ follows a design trail originally blazed by the Yeezy 500 in November 2018. Like its predecessor',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 350 V2 Zebra",
		slug: "yeezy-boost-350-v2-zebra-cp9654",
		color: "White",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/014/979/033/original/105568_00.png.png",
		shortDescription: '"Released on February 25',
		longDescription: '"Released on February 25',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 2,
		name: "NMD R1 Speckle Pack White",
		slug: "nmd_r1-speckle-pack-white-ef3326",
		color: "White",
		price: 130,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/020/249/956/original/EF3326.png.png",
		shortDescription: "The adidas is a White sneaker from adidas.",
		longDescription: null,
		isAvailable: true,
		isNew: true,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 350 V2 Ice Yellow",
		slug: "yeezy-boost-350-v2-ice-yellow-f36980",
		color: "Yellow",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/012/598/505/original/348063_00.png.png",
		shortDescription: '"Kanye West and adidas continued their partnership with the Yeezy Boost 350 V2 ‘Butter',
		longDescription: '"Kanye West and adidas continued their partnership with the Yeezy Boost 350 V2 ‘Butter',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
	{
		brandId: 2,
		name: "Yeezy Boost 350 V2 Semi Frozen Yellow",
		slug: "yeezy-boost-350-v2-b37572",
		color: "Yellow",
		price: 220,
		image:
			"https://image.goat.com/750/attachments/product_template_pictures/images/016/928/118/original/155573_00.png.png",
		shortDescription: '"Kanye West’s Yeezy Boost 350 V2 in Semi Frozen Yellow first hit stores in November 2017',
		longDescription: '"Kanye West’s Yeezy Boost 350 V2 in Semi Frozen Yellow first hit stores in November 2017',
		isAvailable: true,
		isNew: false,
		status: "active",
	},
];
