/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSneakersRouteImport } from './routes/admin.sneakers'
import { Route as SneakerSlugRouteImport } from './routes/sneaker.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSneakersRoute = AdminSneakersRouteImport.update({
  id: '/sneakers',
  path: '/sneakers',
  getParentRoute: () => AdminRoute,
} as any)
const SneakerSlugRoute = SneakerSlugRouteImport.update({
  id: '/sneaker/$slug',
  path: '/sneaker/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sneakers': typeof AdminSneakersRoute
  '/sneaker/$slug': typeof SneakerSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/favorites': typeof FavoritesRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sneakers': typeof AdminSneakersRoute
  '/sneaker/$slug': typeof SneakerSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sneakers': typeof AdminSneakersRoute
  '/sneaker/$slug': typeof SneakerSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/favorites'
    | '/admin/brands'
    | '/admin/login'
    | '/admin/sneakers'
    | '/sneaker/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/favorites'
    | '/admin/brands'
    | '/admin/login'
    | '/admin/sneakers'
    | '/sneaker/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/favorites'
    | '/admin/brands'
    | '/admin/login'
    | '/admin/sneakers'
    | '/sneaker/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  SneakerSlugRoute: typeof SneakerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sneakers': {
      id: '/admin/sneakers'
      path: '/sneakers'
      fullPath: '/admin/sneakers'
      preLoaderRoute: typeof AdminSneakersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sneaker/$slug': {
      id: '/sneaker/$slug'
      path: '/sneaker/$slug'
      fullPath: '/sneaker/$slug'
      preLoaderRoute: typeof SneakerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSneakersRoute: typeof AdminSneakersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandsRoute: AdminBrandsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSneakersRoute: AdminSneakersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  SneakerSlugRoute: SneakerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
